/*
 * Agnes@needemand
 */
package views;


/**
 *
 * @author agnes
 */
public class BeanFeature extends javax.swing.JPanel {

    private String title = "titre";
    private int val = 5;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        jLabel1.setText(title);
        this.title = title;
    }

    public int getVal() {
        return val;
    }

    public void setVal(int val) {
        jProgressBar1.setValue(val);
        this.val = val;
    }

    /**
     * Creates new form BeanFeature
     */
    public BeanFeature() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        jLabel1.setText("jLabel1");
        add(jLabel1);
        add(jProgressBar1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

}
